### ISSUE TITLE
hive 'editable' property value not identical for hives vs. groups endpoint

### ISSUE THREAD

**Issue by JuliaBD** [beepnl/BEEP#77] opened 2020-12-17 10:53 UTC
At the test database, the following occurs:
When reading a hive object via the hives endpoint, the 'editable' prop is set to false
When reading the same hive via the groups endpoint, the 'editable' prop is set to true.

Expected behaviour:
The 'editable' values should be identical, either both false or both true.

Which value is expected?
This occurs with a hive in a shared apiary of which I am not the owner, but an admin member. So I think both 'editable' values should be true, for admin members?

(P.S. when trying to edit this hive, there's a bug on the hive-edit page which is fixed on local already, but not in the latest build yet)

**Comment by pvgennip** [comment] 2020-12-21 16:33
Fixed, now transferred to Hive model.
Live at test server. Can you please check if the issue is resolved?

**Closed by pvgennip** 2020-12-21 16:33 UTC
Labels: bug
